updated organisation sql script, and modified directory to handle the directory_entry_name correctly

diff --git a/design/process-societies b/design/process-societies
--- a/design/process-societies
+++ b/design/process-societies
@@ -1,8 +1,13 @@
 #!/bin/bash
 
 # Input and output files
-input=societies.data
-output=societies.sql
+input="societies.data"
+output="societies.sql"
+
+if [ ! -e $input ]; then
+	echo 1>&2 "$input not found"
+	exit 1;
+fi
 
 # end of line comment
 comment="--"
@@ -10,21 +15,7 @@ comment="--"
 input_format_seg="\(.*\)"
 input_format="^$input_format_seg@@$input_format_seg@@$input_format_seg$"
 
-prefix="INSERT INTO \\\`entities\\\` \(\\\`entity_deleted\\\` \\)  VALUES \(\\'0\\'\);\\
-INSERT INTO \\\`organisations\\\` \\(\\
-  \\\`organisation_entity_id\\\` ,\\
-  \\\`organisation_organisation_type_id\\\` ,\\
-  \\\`organisation_name\\\` ,\\
-  \\\`organisation_description\\\` ,\\
-  \\\`organisation_url\\\` ,\\
-  \\\`organisation_directory\\\` ,\\
-  \\\`organisation_events\\\` ,\\
-  \\\`organisation_hits\\\` \)\\
-VALUES \\( LAST_INSERT_ID\\(\\), \\'2\\', \\'"
-middle1="\\', \\'"
-middle2="\\', \\\""
-postfix="\\\" , \\'1\\', \\'1\\', \\'0\\' \\);\\
-"
+max_directory_entry_name=30
 
 # header
 echo "$comment Generated by process-societies" > $output
@@ -41,5 +32,28 @@ echo "$comment DELETE FROM \`entities\`;" >> $output
 echo "$comment DELETE FROM \`organisations\`;" >> $output
 echo "" >> $output
 
-sed "s/$input_format/$prefix\1$middle1\2$middle2\3$postfix/" < $input >> $output
-#echo "s/$input_format/$prefix\1$middle1\2$middle2\3$postfix/"
+while read line
+do
+	name=`echo "$line" | sed "s/$input_format/\1/"`
+	description=`echo "$line" | sed "s/$input_format/\2/"`
+	url=`echo "$line" | sed "s/$input_format/\3/"`
+	
+	directory_entry=`echo "$name" | sed "s/ /_/g"`
+	directory_entry=`echo "$directory_entry" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"`
+	directory_entry=`echo "$directory_entry" | sed "s/[^0-9a-z_]//g"`
+	directory_entry=`echo "$directory_entry" | sed "s/__/_/g"`
+	directory_entry=${directory_entry:0:max_directory_entry_name}
+	
+	echo "INSERT INTO \`entities\` (\`entity_deleted\` )  VALUES ('0');
+INSERT INTO \`organisations\` (
+  \`organisation_entity_id\` ,
+  \`organisation_organisation_type_id\` ,
+  \`organisation_name\` ,
+  \`organisation_description\` ,
+  \`organisation_url\` ,
+  \`organisation_directory_entry_name\` ,
+  \`organisation_events\` ,
+  \`organisation_hits\` )
+VALUES ( LAST_INSERT_ID(), '2', '$name', '$description', \"$url\" , '$directory_entry', '1', '0' );
+" >> $output
+done < $input
